---
- name: Deploy Cisco Secure Client - Force Download & Install
  hosts: windows
  gather_facts: no
  vars:
    # Double check this filename exists in your GitHub repo!
    zip_url: "https://github.com/coderun23-cloud/windows-automation/raw/main/cisco_install.zip"
    temp_dir: "C:\\CiscoUpdate"
    version: "5.1.14.145"

  tasks:
    - name: 1. Prepare Environment
      ansible.windows.win_shell: |
        if (Test-Path "{{ temp_dir }}") { Remove-Item "{{ temp_dir }}" -Recurse -Force }
        New-Item -Path "{{ temp_dir }}" -ItemType Directory

    - name: 2. Download ZIP (PowerShell Force TLS 1.2)
      ansible.windows.win_shell: |
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest -Uri "{{ zip_url }}" -OutFile "{{ temp_dir }}\\cisco.zip" -TimeoutSec 600

    - name: 3. Extract Files
      ansible.windows.win_shell: |
        Expand-Archive -Path "{{ temp_dir }}\\cisco.zip" -DestinationPath "{{ temp_dir }}" -Force

    - name: 4. Install All Modules
      ansible.windows.win_package:
        path: "{{ temp_dir }}\\{{ item }}"
        arguments: "/norestart /passive /quiet"
        state: present
      loop:
        - "cisco-secure-client-win-{{ version }}-core-vpn-predeploy-k9.msi"
        - "cisco-secure-client-win-{{ version }}-iseposture-predeploy-k9.msi"
        - "cisco-secure-client-win-{{ version }}-nvm-predeploy-k9.msi"
        - "cisco-secure-client-win-{{ version }}-nam-predeploy-k9.msi"

    - name: 5. Cleanup
      ansible.windows.win_file:
        path: "{{ temp_dir }}\\cisco.zip"
        state: absent