---
- name: Discover Cisco Secure Client Details
  hosts: windows
  tasks:
    - name: Get Package Details
      ansible.windows.win_shell: |
        # Using the exact name string found in your PS output
        Get-Package -Name "Cisco Secure Client - AnyConnect VPN" | Select-Object Name, Version, FastPackageID | ConvertTo-Json
      register: package_details

    - name: Get Service Status
      ansible.windows.win_service:
        # vsc_agent is the standard service for version 5.x
        name: vsc_agent
      register: service_details

    - name: Check Installation Directory
      ansible.windows.win_stat:
        # Path updated based on your File Explorer screenshot
        path: 'C:\Program Files (x86)\Cisco\Cisco Secure Client'
      register: folder_details

    - name: Display Summary for Demo
      ansible.builtin.debug:
        msg: 
          - "Software Name: {{ (package_details.stdout | from_json).Name }}"
          - "Version: {{ (package_details.stdout | from_json).Version }}"
          - "Product ID (GUID): {{ (package_details.stdout | from_json).FastPackageID }}"
          - "Service Status: {{ service_details.state | default('Not Found') }}"
          - "Secure Client Folder Exists: {{ folder_details.stat.exists }}"
