---
- name: Deploy Cisco Secure Client from GitHub (Native PS Version)
  hosts: windows
  gather_facts: no
  vars:
    # Use the 'Raw' link to your ZIP file on GitHub
    zip_url: "https://github.com/coderun23-cloud/windows-automation/raw/main/cisco_install.zip"
    temp_dir: "C:\\CiscoUpdate"
    version: "5.1.14.145"

  tasks:
    - name: 1. Create Temp Directory
      ansible.windows.win_shell: |
        if (!(Test-Path "{{ temp_dir }}")) { New-Item -Path "{{ temp_dir }}" -ItemType Directory }

    - name: 2. Download ZIP from GitHub
      ansible.windows.win_get_url:
        url: "{{ zip_url }}"
        dest: "{{ temp_dir }}\\cisco.zip"
        timeout: 600

    - name: 3. Extract Files using Native PowerShell
      ansible.windows.win_shell: |
        Expand-Archive -Path "{{ temp_dir }}\\cisco.zip" -DestinationPath "{{ temp_dir }}" -Force

    - name: 4. Install Modules (VPN, Posture, NVM, NAM)
      ansible.windows.win_package:
        path: "{{ temp_dir }}\\{{ item }}"
        arguments: "/norestart /passive /quiet"
        state: present
      loop:
        - "cisco-secure-client-win-{{ version }}-core-vpn-predeploy-k9.msi"
        - "cisco-secure-client-win-{{ version }}-iseposture-predeploy-k9.msi"
        - "cisco-secure-client-win-{{ version }}-nvm-predeploy-k9.msi"
        - "cisco-secure-client-win-{{ version }}-nam-predeploy-k9.msi"

    - name: 5. Cleanup ZIP File
      ansible.windows.win_file:
        path: "{{ temp_dir }}\\cisco.zip"
        state: absent