---
- name: Deploy Cisco Secure Client from GitHub
  hosts: windows
  gather_facts: no
  vars:
    # IMPORTANT: Upload a .zip of your folder to GitHub and use the 'Raw' link here
    zip_url: "https://github.com/coderun23-cloud/windows-automation/raw/main/cisco_install.zip"
    temp_dir: "C:\\CiscoUpdate"
    version: "5.1.14.145"

  tasks:
    - name: 1. Clean and Create Temp Directory
      ansible.windows.win_file:
        path: "{{ temp_dir }}"
        state: "{{ item }}"
      loop: [absent, directory]

    - name: 2. Download 100MB+ Zip from GitHub
      ansible.windows.win_get_url:
        url: "{{ zip_url }}"
        dest: "{{ temp_dir }}\\cisco.zip"
        timeout: 600 # Increased timeout for larger file

    - name: 3. Extract Installation Files
      community.windows.win_unzip:
        src: "{{ temp_dir }}\\cisco.zip"
        dest: "{{ temp_dir }}"
        delete_archive: yes

    - name: 4. Install Specific Modules (Silent)
      ansible.windows.win_package:
        path: "{{ temp_dir }}\\{{ item }}"
        arguments: "/norestart /passive /quiet"
        state: present
      loop:
        - "cisco-secure-client-win-{{ version }}-core-vpn-predeploy-k9.msi"
        - "cisco-secure-client-win-{{ version }}-iseposture-predeploy-k9.msi"
        - "cisco-secure-client-win-{{ version }}-nvm-predeploy-k9.msi"
        - "cisco-secure-client-win-{{ version }}-nam-predeploy-k9.msi"

    - name: 5. Verification - Check for UI
      ansible.windows.win_stat:
        path: "C:\\Program Files (x86)\\Cisco\\Cisco Secure Client\\csc_ui.exe"
      register: ui_check

    - name: 6. Final Status
      ansible.builtin.debug:
        msg: "Installation Successful"
      when: ui_check.stat.exists