---
- name: Migration - Uninstall AnyConnect and Install Secure Client 5.1.14
  hosts: windows
  tasks:
    - name: 1. Identify Legacy AnyConnect Product ID
      ansible.windows.win_shell: |
        (Get-Package -Name "*AnyConnect*").FastPackageID
      register: legacy_id

    - name: 2. Create Temp Folder for new client
      ansible.windows.win_file:
        path: C:\CiscoUpgrade
        state: directory

    - name: 3. Copy New Version (5.1.14.145) to VM
      ansible.windows.win_copy:
        src: files/cisco-secure-client-win-5.1.14.145/
        dest: C:\CiscoUpgrade\

    - name: 4. Install Cisco Secure Client Core VPN
      ansible.windows.win_package:
        path: C:\CiscoUpgrade\cisco-secure-client-win-5.1.14.145-core-vpn-predeploy-k9.msi
        arguments: '/norestart /passive /quiet'
        state: present

    - name: 5. Verify New Service
      ansible.windows.win_service:
        name: vsc_agent
        state: started
