---
- name: Total Cleanup - Force Remove Cisco Components
  hosts: windows
  gather_facts: no

  tasks:
    - name: 1. Stop all Cisco Services (Unlocks files)
      ansible.windows.win_shell: |
        $services = Get-Service -Name "vpnagent", "aciscoposture", "nvm_service", "csc_*" -ErrorAction SilentlyContinue
        foreach ($s in $services) {
            Stop-Service $s.Name -Force -ErrorAction SilentlyContinue
            Write-Output "Stopped $($s.Name)"
        }
        # Kill any remaining Cisco processes
        Get-Process -Name "Cisco*", "csc*" -ErrorAction SilentlyContinue | Stop-Process -Force

    - name: 2. Deep Clean Uninstall via MSI
      ansible.windows.win_shell: |
        $apps = Get-Package -Name "*Cisco Secure Client*", "*AnyConnect*" -ErrorAction SilentlyContinue
        foreach ($app in $apps) {
            msiexec.exe /x $app.FastPackageID /qn /norestart
        }

    - name: 3. Remove Leftover Folders (Should work now)
      ansible.windows.win_file:
        path: "{{ item }}"
        state: absent
      loop:
        - "C:\\Program Files (x86)\\Cisco\\Cisco Secure Client"
        - "C:\\Program Data\\Cisco"
      register: folder_removal
      ignore_errors: yes

    - name: 4. Final Status
      ansible.builtin.debug:
        msg: "Cleanup finished. If Search still shows the icon, a reboot is required to clear the Windows Icon Cache."