---
- name: Total Cleanup - Remove All Cisco Secure Client Components
  hosts: windows
  gather_facts: no

  tasks:
    - name: 1. Deep Clean Uninstall
      ansible.windows.win_shell: |
        # Find every package that matches Cisco Secure Client or AnyConnect
        $apps = Get-Package -Name "*Cisco Secure Client*", "*AnyConnect*" -ErrorAction SilentlyContinue
        
        foreach ($app in $apps) {
            Write-Output "Removing: $($app.Name)"
            msiexec.exe /x $app.FastPackageID /qn /norestart
        }
      register: cleanup_result

    - name: 2. Remove Leftover Folders
      ansible.windows.win_file:
        path: "{{ item }}"
        state: absent
      loop:
        - "C:\\Program Files (x86)\\Cisco\\Cisco Secure Client"
        - "C:\\ProgramData\\Cisco\\Cisco Secure Client"

    - name: 3. Final Search Result
      ansible.builtin.debug:
        msg: "{{ cleanup_result.stdout_lines if cleanup_result.stdout_lines else 'No Cisco components found.' }}"